### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by laryn** [dervishmoose/classy_paragraphs_ui#15]
Is this code released under the same license as Drupal modules that are listed on Drupal.org? (ie. GPL-2.0 or later) I'm thinking of porting Classy Paragraphs to Backdrop and incorporating this code in as long as the license is compatible.

**Comment by laryn** [comment]
@dervishmoose Can you clarify the license on this module? (Just trying to make sure it's fair game for inclusion in a GPL-2.0 or later release).

**Comment by dervishmoose** [comment]
Hello, and Thank you for following up on the question. Yes, the intent is to offer this module for community use and have always considered it in GPL. I would love it see it ported to backdrop.  What do you need from me to document as GPL?

**Comment by laryn** [comment]
Thanks @dervishmoose that's great! Here's a PR to specify the license. If it looks good you should be able to merge it and have the license stated explicitly in the repo.

https://github.com/dervishmoose/classy_paragraphs_ui/pull/16

**Comment by laryn** [comment]
@dervishmoose Thanks! It's now included in the [Backdrop CMS version of Classy Paragraphs](https://github.com/backdrop-contrib/classy_paragraphs)!
