### ISSUE TITLE
Implement hook_uninstall

### ISSUE THREAD

**Issue by deadeye017** [dervishmoose/classy_paragraphs_ui#2]
This module sets variables using variable_set. If the module is uninstalled, then these variables should be removed. Check out [hook_uninstall](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_uninstall/7) and [variable_del](https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/variable_del/7).

**Comment by dervishmoose** [comment]
First off, Thank you for your suggestion. I am unsure of the future of this module. I built it originally with the intent of turning over the code to the project maintainer of classy_paragraphs. If that happens the uninstall should happen in the classy_paragraphs module. I am unsure how best to proceed, if it would make sense to remove the settings on uninstall or if there will be an upgrade path. I need to have a talk with the project maintainer of classy_paragraphs.

**Comment by deadeye017** [comment]
Thanks for your reply! I imagined that you would want to merge this into
classy_paragraphs, which is totally the way to go. However, as it stands
right now, if you a site builder installs this module, then your variables
would be stored in their database. It's not a super big deal, and it's also
easy to wire up (also, see my other pull requests :) )

I'm glad you took initiative to get some sort of UI on to github so that
users of classy_paragraphs don't have to write their own hooks.

DL

**Comment by dervishmoose** [comment]
Thanks, pull request merged.
